version: '3'

services:
  postgres_db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    image: smartfinance
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  pg_data: