version: '3.8'
services:
  database:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: