version: '3'

services:
  postgres_db:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    image: smartfinance
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_USER=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  grafana:
    build: './config/grafana'
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
        - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

volumes:
  pg_data:
  grafana-storage:
  prometheus-storage:
