spring:
  datasource:
    username: "${PG_USERNAME:admin}"
    password: "${PG_PASSWORD:admin}"
    url: "jdbc:postgresql://${PG_HOST:localhost:5432}/${PG_DB:postgres}"
messaging:
  queue:
    name: "reports"
  topic:
    name: "finance"
  routing:
    key: "rnd.key.#"
